name: Test and publish package

on:
  release:
    types: [publish]

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build package
        run: yarn build

      - name: Test package
        run: yarn test

      - name: Publish package
        run: yarn lerna:publish
