name: Run tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build package
        run: yarn build

      - name: Test package
        run: yarn test
